name: comrade_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  html_unescape: ^1.0.2
  http: