name: Deploy image Docker

on:
  push:
    paths:
      - 'image/**'
      - '.github/workflows/main.yml'
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Image to Heroku
        uses: meska/heroku-deploy@f6ff8db5e943fe0398a663d92f300cdd428d57e1
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          dockerfile_directory: 'image'